# fly.toml file generated for pizzamngrclient on 2023-01-19T02:41:50-07:00

app = "pizzamngrclient"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
REACT_APP_API_BASE_URL = "https://pizzamngrapi.fly.dev"

[experimental]
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
