version: '3.9'
services:
  client:
    image: pizza-manager-client
    container_name: pizza_mngr_client
    restart: always
    build:
      context: client
      dockerfile: Dockerfile
    environment:
    - WATCHPACK_POLLING=true
    ports:
      - 3000:3000
    depends_on:
      - api
    volumes:
      - ./client:/usr/src/client
      - /client/node_modules
    links:
      - api
    networks:
      - pizza-manager-network
  api:
    image: pizza-manager-api
    container_name: pizza_mngr_api
    restart: unless-stopped
    build:
      context: api
      dockerfile: Dockerfile
    environment:
    - CHOKIDAR_USEPOLLING=true
    ports: 
      - 5000:5000
    depends_on:
      - db
    volumes:
      - ./api:/usr/src/api
      - /api/node_modules
  db:
    image: postgres:11.5
    container_name: pizza_mngr_db
    restart: always
    environment:
      - POSTGRES_USER=pizza_manager
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=pizza_manager
    ports:
      - 5432:5432
    networks:
      - pizza-manager-network
    volumes:
      - ./postgres-db:/var/lib/postgresql/data
  pgadmin:
      container_name: pizza_mngr_pgadmin4
      image: dpage/pgadmin4
      restart: always
      environment:
        PGADMIN_DEFAULT_EMAIL: admin@admin.com
        PGADMIN_DEFAULT_PASSWORD: root
      ports:
        - "5050:80"
      networks:
      - pizza-manager-network
networks:
  pizza-manager-network:
    