version: '3.9'
services:
  client:
    image: pizza-manager-client
    restart: always
    build:
      context: client
      dockerfile: Dockerfile
    environment:
    - WATCHPACK_POLLING=true
    ports:
      - 3000:3000
    depends_on:
      - api
    volumes:
      - ./client:/usr/src/client
      - /client/node_modules
    links:
      - api
  api:
    image: pizza-manager-api
    restart: unless-stopped
    build:
      context: api
      dockerfile: Dockerfile
    environment:
    - CHOKIDAR_USEPOLLING=true
    - DB_USER=pizza_manager
    - DB_PASSWORD=123
    - DB_NAME=pizza_manager
    ports: 
      - 5000:5000
    depends_on:
      - db
    volumes:
      - ./api:/usr/src/api
      - /api/node_modules
  db:
    image: postgres:11.5
    restart: always
    environment:
      - POSTGRES_USER=pizza_manager
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=pizza_manager
    ports:
      - 5432:5432
    volumes:
      - postgresDB:/var/lib/postgresql/data
  testDB:
    image: postgres:11.5
    restart: always
    environment:
      - POSTGRES_USER=test_user
      - POSTGRES_PASSWORD=test_123
      - POSTGRES_DB=e2e_tests
    ports:
      - 5433:5432
  pgadmin:
      image: dpage/pgadmin4
      restart: always
      environment:
        PGADMIN_DEFAULT_EMAIL: admin@admin.com
        PGADMIN_DEFAULT_PASSWORD: root
      ports:
        - "5050:80"
      volumes:
        - pgadmin-data:/var/lib/pgadmin
volumes:
  postgresDB:
  pgadmin-data:
    