version: '3.9'
services:
  client:
    image: ismandycoding.azurecr.io/pizza-manager-client
    domainname: pizzaapp
    restart: always
    build:
      context: client
      dockerfile: Dockerfile
    environment:
    - REACT_APP_API_BASE_URL=http://localhost:5000
    - PORT=80
    ports:
      - 80:80
    depends_on:
      - api
  api:
    image: ismandycoding.azurecr.io/pizza-manager-api
    domainname: pizzaapp
    restart: unless-stopped
    build:
      context: api
      dockerfile: Dockerfile
    environment:
    - DB_HOST=http://localhost:5432
      # This is for temporary demo purposes - 
      # A completed version of this would use Docker Secrets
    - DB_USER=pizza_manager
    - DB_PASSWORD=123
    - DB_NAME=pizza_manager
    ports: 
      - 5000:5000
    depends_on:
      - db
  db:
    image: postgres:11.5
    restart: always
    environment:
      # This is for temporary demo purposes - 
      # A completed version of this would use Docker Secrets
      - POSTGRES_USER=pizza_manager
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=pizza_manager
    ports:
      - 5432:5432
    volumes:
      - postgresdbvol:/var/lib/postgresql/data
volumes:
  postgresdbvol:
    driver: azure_file
    driver_opts:
      share_name: pizzafileshare
      storage_account_name: ismandycodingpizza